"""Typed schema for everything that flows through the engine.

Kept narrow on purpose — these are the contract between modules. Adding
fields is cheap; renaming them later is expensive.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---- Domain enums ----------------------------------------------------------


class PersonaArchetype(str, Enum):
    """India-tuned persona buckets. Used as priors; the actual persona
    text is generated by the LLM conditioned on the bucket."""

    METRO_PROFESSIONAL = "metro_professional"
    TIER2_WORKING_PROFESSIONAL = "tier2_working_professional"
    COLLEGE_STUDENT = "college_student"
    SMALL_BUSINESS_OWNER = "small_business_owner"
    HOMEMAKER_URBAN = "homemaker_urban"
    HOMEMAKER_RURAL = "homemaker_rural"
    SENIOR_CITIZEN = "senior_citizen"
    CREATOR_INFLUENCER = "creator_influencer"
    POLITICAL_PARTISAN = "political_partisan"
    ACTIVIST_ORGANIZER = "activist_organizer"
    INVESTOR_FOUNDER = "investor_founder"
    FARMER_AGRARIAN = "farmer_agrarian"
    DAILY_WAGE_WORKER = "daily_wage_worker"
    RELIGIOUS_COMMUNITY_MEMBER = "religious_community_member"
    RETIRED_GOVT_SERVANT = "retired_govt_servant"


class Language(str, Enum):
    ENGLISH = "en"
    HINDI = "hi"
    BENGALI = "bn"
    TAMIL = "ta"
    TELUGU = "te"
    MARATHI = "mr"
    GUJARATI = "gu"
    KANNADA = "kn"
    MALAYALAM = "ml"
    PUNJABI = "pa"
    HINGLISH = "hinglish"
    TANGISH = "tanglish"
    BHINGLISH = "bhinglish"


class RelationshipKind(str, Enum):
    FOLLOWS = "follows"
    FRIEND_OF = "friend_of"
    FAMILY_OF = "family_of"
    COLLEAGUE_OF = "colleague_of"
    OPPOSES = "opposes"
    SUPPORTS = "supports"
    CUSTOMER_OF = "customer_of"
    RIVAL_OF = "rival_of"


# ---- Graph layer -----------------------------------------------------------


class Entity(BaseModel):
    id: str
    type: str  # Person, Organization, Product, Event, Location, Policy, ...
    name: str
    attrs: dict[str, Any] = Field(default_factory=dict)


class Relation(BaseModel):
    src: str
    dst: str
    kind: str
    weight: float = 1.0
    attrs: dict[str, Any] = Field(default_factory=dict)


class KnowledgeGraph(BaseModel):
    entities: list[Entity] = Field(default_factory=list)
    relations: list[Relation] = Field(default_factory=list)


# ---- Persona layer ---------------------------------------------------------


class Persona(BaseModel):
    id: str
    name: str
    archetype: PersonaArchetype
    language: Language
    city_tier: int = Field(ge=1, le=3)  # 1 = metro, 2 = tier-2, 3 = tier-3/rural
    age: int = Field(ge=14, le=90)
    gender: str
    occupation: str
    political_lean: str = "centrist"  # leftist, centrist, rightist, apolitical
    religiosity: str = "moderate"  # secular, moderate, devout
    socioeconomic_class: str = "middle"  # lower, lower-middle, middle, upper-middle, upper
    media_diet: list[str] = Field(default_factory=list)
    key_concerns: list[str] = Field(default_factory=list)
    bio: str  # 2-4 sentence backstory used by the agent
    initial_opinion: str  # their take on the seed topic, in their own voice


# ---- Agent memory / message layer ------------------------------------------


class AgentMessage(BaseModel):
    """A single utterance / post / DM / broadcast."""

    sender_id: str
    content: str
    language: Language
    round: int
    visibility: str = "public"  # public, group, dm
    audience: list[str] = Field(default_factory=list)  # agent ids; empty = public
    sentiment: float = 0.0  # -1..+1
    importance: float = 0.5  # 0..1; used for memory compression
    created_at: datetime = Field(default_factory=datetime.utcnow)


class AgentMemory(BaseModel):
    """Per-agent memory summary. Full transcript is in the run log; this is
    the compressed view that the LLM sees at decision time."""

    persona_id: str
    round: int
    short_term: list[str] = Field(default_factory=list)  # last 5 events verbatim
    long_term_summary: str = ""  # rolling summary of prior rounds
    stance_shift: float = 0.0  # net movement on -1..+1 since start
    trust_scores: dict[str, float] = Field(default_factory=dict)  # peer -> trust
    emotional_state: str = "neutral"


# ---- Simulation core -------------------------------------------------------


class SimConfig(BaseModel):
    name: str
    seed_topic: str
    domain: str  # "consumer" | "political" | "campus" | "startup" | "custom"
    max_rounds: int = 20
    population_size: int = 80
    language_mix: dict[Language, float] = Field(default_factory=dict)
    archetype_mix: dict[PersonaArchetype, int] = Field(default_factory=dict)
    god_variables: list[str] = Field(default_factory=list)
    """Operator-injected perturbations to apply mid-simulation. e.g.
    ['news_bomb:Government announces 5% GST on fantasy apps']."""


class SimRound(BaseModel):
    round: int
    messages: list[AgentMessage] = Field(default_factory=list)
    god_event: str | None = None


class SimResult(BaseModel):
    config: SimConfig
    graph: KnowledgeGraph
    personas: list[Persona]
    rounds: list[SimRound] = Field(default_factory=list)
    report_markdown: str = ""
    started_at: datetime = Field(default_factory=datetime.utcnow)
    finished_at: datetime | None = None